import { IBase } from '@/database/interfaces/base.interface';
import { ITeam } from '@/employee-management/teams/interfaces/team.interface';
import { Membership } from '@/memberships/entities/membership.entity';
import { Role } from '@/roles/entities/role.entity';

export interface IOrganization extends IBase {
  name?: string;
  subdomain?: string;
  domain?: string;
  street?: string;
  zip?: string;
  city?: string;
  country?: string;
  phone?: string;
  email?: string;
  website?: string;
  timezone: string;
  schoolYearStartMonth: number;
  schoolYearStartDay: number;
  latitude?: number;
  longitude?: number;
  shortCode?: string;
  schoolType?: string;
  legalEntity?: string;
  language?: string;
  logoUrl?: string;
  state?: string;
  billingAddressSameAsLocation?: boolean;
  billingAddressExtra?: string;
  contactName?: string;
  contactRole?: string;
  contactEmail?: string;
  contactPhone?: string;
  billingEmail?: string;
  parentMailSenderEmail?: string;
  currentSchoolYear?: string;
  activeLevels?: string[];
  plan?: string;
  userLicenseLimit?: number;
  contractEndsAt?: string;
  billingInterval?: string;
  billingAmountChf?: number;
  storageLimitGb?: number;
  lifecycleStatus?: string;
  trialEndsAt?: string;
  suspendedAt?: Date;
  suspendedReason?: string;
  suspendedById?: string;
  memberships?: Membership[];
  roles?: Role[];
  teams?: ITeam[];
}
