// roles/seeds/assign-permissions-to-system-roles.seeder.ts
import { EntityManager, In } from 'typeorm';
import { Role } from '@/roles/entities/role.entity';
import { Permission } from '@/permissions/entities/permission.entity';
import { SystemRole } from '../entities/system-role.enum';
import { PermissionCode } from '@/permissions/entities/permission-code.enum';

const MATRIX: Record<SystemRole, PermissionCode[]> = {
  ORG_OWNER: [
    'ORG_DELETE',
    'ORG_TRANSFER_OWNERSHIP',
    'BILLING_MANAGE',
    'USER_INVITE',
    'USER_REMOVE',
    'ROLE_CREATE',
    'ROLE_DELETE',
    'ROLE_ASSIGN',
    'TEAM_CREATE',
    'TEAM_DELETE',
    'TEAM_MANAGE',
    'EMPLOYEE_READ',
    'EMPLOYEE_WRITE',
    'EMPLOYEE_ABSENCE_CATEGORY_READ',
    'EMPLOYEE_ABSENCE_CATEGORY_MANAGE',
    'TIMESHEET_READ',
    'TIMESHEET_WRITE',
    'SCHOOL_CLASS_READ',
    'SCHOOL_CLASS_WRITE',
    'SCHOOL_CLASS_DELETE',
    'CONTACT_PERSON_READ',
    'CONTACT_PERSON_WRITE',
    'CONTACT_PERSON_DELETE',
    'ADMISSION_STAGE_READ',
    'ADMISSION_STAGE_MANAGE',
    'ADMISSION_APPLICATION_READ',
    'ADMISSION_APPLICATION_WRITE',
    'ADMISSION_APPLICATION_MOVE',
    'ADMISSION_APPLICATION_ENROLL',
    'ADMISSION_APPLICATION_DELETE',
    'FAMILY_READ',
    'FAMILY_WRITE',
    'CURRICULUM_LEVEL_READ',
    'CURRICULUM_LEVEL_MANAGE',
    'CURRICULUM_READ',
    'CURRICULUM_MANAGE',
    'RECORD_KEEPING_READ',
    'RECORD_KEEPING_WRITE',
    'RECORD_KEEPING_SETTINGS_MANAGE',
    'ADDRESS_READ',
    'ADDRESS_WRITE',
    'ADDRESS_DELETE',
    'PROJECT_READ',
    'PROJECT_CREATE',
    'PROJECT_MANAGE_ALL',
    'PROJECT_TEMPLATE_MANAGE',
    'PROTOCOL_READ',
    'PROTOCOL_WRITE',
    'PROTOCOL_DELETE',
    'CONSENT_READ',
    'CONSENT_MANAGE',
    'CONSENT_SETTINGS_MANAGE',
    'DATA_REQUEST_READ',
    'DATA_REQUEST_MANAGE',
    'RETENTION_READ',
    'RETENTION_MANAGE',
    'DATA_BREACH_READ',
    'DATA_BREACH_MANAGE',
  ] as PermissionCode[],
  ORG_ADMIN: [
    'USER_INVITE',
    'USER_REMOVE',
    'ROLE_CREATE',
    'ROLE_ASSIGN',
    'TEAM_CREATE',
    'TEAM_DELETE',
    'TEAM_MANAGE',
    'EMPLOYEE_READ',
    'EMPLOYEE_WRITE',
    'EMPLOYEE_ABSENCE_CATEGORY_READ',
    'EMPLOYEE_ABSENCE_CATEGORY_MANAGE',
    'TIMESHEET_READ',
    'TIMESHEET_WRITE',
    'SCHOOL_CLASS_READ',
    'SCHOOL_CLASS_WRITE',
    'SCHOOL_CLASS_DELETE',
    'CONTACT_PERSON_READ',
    'CONTACT_PERSON_WRITE',
    'CONTACT_PERSON_DELETE',
    'ADMISSION_STAGE_READ',
    'ADMISSION_STAGE_MANAGE',
    'ADMISSION_APPLICATION_READ',
    'ADMISSION_APPLICATION_WRITE',
    'ADMISSION_APPLICATION_MOVE',
    'ADMISSION_APPLICATION_ENROLL',
    'ADMISSION_APPLICATION_DELETE',
    'FAMILY_READ',
    'FAMILY_WRITE',
    'CURRICULUM_LEVEL_READ',
    'CURRICULUM_LEVEL_MANAGE',
    'CURRICULUM_READ',
    'CURRICULUM_MANAGE',
    'RECORD_KEEPING_READ',
    'RECORD_KEEPING_WRITE',
    'RECORD_KEEPING_SETTINGS_MANAGE',
    'ADDRESS_READ',
    'ADDRESS_WRITE',
    'ADDRESS_DELETE',
    'PROJECT_READ',
    'PROJECT_CREATE',
    'PROJECT_MANAGE_ALL',
    'PROJECT_TEMPLATE_MANAGE',
    'PROTOCOL_READ',
    'PROTOCOL_WRITE',
    'PROTOCOL_DELETE',
    'CONSENT_READ',
    'CONSENT_MANAGE',
    'CONSENT_SETTINGS_MANAGE',
    'DATA_REQUEST_READ',
    'DATA_REQUEST_MANAGE',
    'RETENTION_READ',
    'RETENTION_MANAGE',
    'DATA_BREACH_READ',
    'DATA_BREACH_MANAGE',
  ] as PermissionCode[],
  HR_MANAGER: [
    'EMPLOYEE_READ',
    'EMPLOYEE_WRITE',
    'EMPLOYEE_ABSENCE_CATEGORY_READ',
    'EMPLOYEE_ABSENCE_CATEGORY_MANAGE',
    'TIMESHEET_READ',
    'TIMESHEET_WRITE',
    'SCHOOL_CLASS_READ',
    'CONTACT_PERSON_READ',
    'ADMISSION_STAGE_READ',
    'CURRICULUM_LEVEL_READ',
    'CURRICULUM_READ',
    'ADDRESS_READ',
    'PROJECT_READ',
    'PROJECT_CREATE',
    'PROTOCOL_READ',
    'PROTOCOL_WRITE',
    'CONSENT_READ',
    'CONSENT_MANAGE',
    'DATA_REQUEST_READ',
    'DATA_REQUEST_MANAGE',
    'RETENTION_READ',
    'DATA_BREACH_READ',
  ] as PermissionCode[],
  OFFICE: [
    'EMPLOYEE_READ',
    'EMPLOYEE_ABSENCE_CATEGORY_READ',
    'TIMESHEET_READ',
    'TIMESHEET_WRITE',
    'SCHOOL_CLASS_READ',
    'SCHOOL_CLASS_WRITE',
    'CONTACT_PERSON_READ',
    'CONTACT_PERSON_WRITE',
    'CONTACT_PERSON_DELETE',
    'ADMISSION_STAGE_READ',
    'ADMISSION_APPLICATION_READ',
    'ADMISSION_APPLICATION_WRITE',
    'ADMISSION_APPLICATION_MOVE',
    'ADMISSION_APPLICATION_ENROLL',
    'ADMISSION_APPLICATION_DELETE',
    'FAMILY_READ',
    'FAMILY_WRITE',
    'CURRICULUM_LEVEL_READ',
    'CURRICULUM_READ',
    'RECORD_KEEPING_READ',
    'RECORD_KEEPING_WRITE',
    'ADDRESS_READ',
    'ADDRESS_WRITE',
    'PROJECT_READ',
    'PROJECT_CREATE',
    'PROJECT_MANAGE_ALL',
    'PROJECT_TEMPLATE_MANAGE',
    'PROTOCOL_READ',
    'PROTOCOL_WRITE',
    'PROTOCOL_DELETE',
    'CONSENT_READ',
    'CONSENT_MANAGE',
    'CONSENT_SETTINGS_MANAGE',
    'DATA_REQUEST_READ',
    'DATA_REQUEST_MANAGE',
    'RETENTION_READ',
    'RETENTION_MANAGE',
    'DATA_BREACH_READ',
    'DATA_BREACH_MANAGE',
  ] as PermissionCode[],
  TEAM_LEAD: [
    'EMPLOYEE_READ',
    'EMPLOYEE_ABSENCE_CATEGORY_READ',
    'TIMESHEET_READ',
    'TIMESHEET_WRITE',
    'TEAM_MANAGE',
    'SCHOOL_CLASS_READ',
    'CONTACT_PERSON_READ',
    'ADMISSION_STAGE_READ',
    'CURRICULUM_LEVEL_READ',
    'CURRICULUM_READ',
    'RECORD_KEEPING_READ',
    'RECORD_KEEPING_WRITE',
    'PROJECT_READ',
    'PROJECT_CREATE',
    'PROTOCOL_READ',
    'PROTOCOL_WRITE',
    'CONSENT_READ',
  ] as PermissionCode[],
  EMPLOYEE: [
    'EMPLOYEE_READ',
    'EMPLOYEE_ABSENCE_CATEGORY_READ',
    'TIMESHEET_READ',
    'TIMESHEET_WRITE',
    'SCHOOL_CLASS_READ',
    'CONTACT_PERSON_READ',
    'ADMISSION_STAGE_READ',
    'CURRICULUM_LEVEL_READ',
    'CURRICULUM_READ',
    'RECORD_KEEPING_READ',
    'RECORD_KEEPING_WRITE',
    'PROJECT_READ',
    'PROJECT_CREATE',
    'PROTOCOL_READ',
    'PROTOCOL_WRITE',
  ] as PermissionCode[],
};

export async function assignPermissionsToOrgSystemRoles(
  m: EntityManager,
  organizationId: string,
) {
  const roles = await m.getRepository(Role).find({
    where: { organizationId, isSystem: true },
    select: ['id', 'systemCode'], // reicht fuer die Zuordnung
  });
  if (!roles.length) return;

  const allCodes = Array.from(new Set(Object.values(MATRIX).flat()));
  const perms = await m
    .getRepository(Permission)
    .find({ where: { code: In(allCodes) } });
  const permByCode = new Map(perms.map((p) => [p.code, p.id]));

  for (const role of roles) {
    const codes = role['systemCode'] ? (MATRIX[role['systemCode']] ?? []) : [];
    const permIds = codes
      .map((c) => permByCode.get(c))
      .filter(Boolean) as string[];
    if (!permIds.length) continue;

    await m
      .createQueryBuilder()
      .relation(Role, 'permissions')
      .of(role.id)
      .add(permIds); // idempotent: keine Duplikate
  }
}
