/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Salbei — mirrors apps/web/app/[locale]/globals.css [data-theme="salbei"]
        background: "#f7f5f0",
        foreground: "#26251f",
        card: "#ffffff",
        "card-foreground": "#26251f",
        primary: "#3a7d44",
        "primary-foreground": "#ffffff",
        secondary: "#f4f1e9",
        "secondary-foreground": "#26251f",
        muted: "#f4f1e9",
        "muted-foreground": "#837d70",
        accent: "#e4efe2",
        "accent-foreground": "#316b3a",
        destructive: "#a3452e",
        "destructive-foreground": "#ffffff",
        border: "#e7e2d7",
        input: "#e7e2d7",
        ring: "#3a7d44",
        sidebar: "#efebe1",
        "sidebar-foreground": "#3d382e",
        "sidebar-border": "#e0dac9",
        "sidebar-accent": "#3a7d44",
        "sidebar-accent-foreground": "#ffffff",
        gold: "#e9c46a",
        "gold-foreground": "#43350e",
        "status-slate-bg": "#efece1",
        "status-slate-fg": "#77705d",
        "status-sky-bg": "#e0ebe8",
        "status-sky-fg": "#2f6459",
        "status-amber-bg": "#f6ecd4",
        "status-amber-fg": "#8a6414",
        "status-green-bg": "#e4efe2",
        "status-green-fg": "#316b3a",
        "status-rose-bg": "#f7e3dd",
        "status-rose-fg": "#a3452e",
      },
      borderRadius: {
        lg: "16px",
        md: "11px",
        sm: "8px",
      },
      fontFamily: {
        sans: ["Geist_400Regular"],
        medium: ["Geist_500Medium"],
        semibold: ["Geist_600SemiBold"],
        bold: ["Geist_700Bold"],
        mono: ["GeistMono_400Regular"],
      },
    },
  },
  plugins: [],
};
