/**
 * The twelve palettes of the design system, extracted from the web app's
 * `app/[locale]/globals.css` so both apps stay on one source of truth. Every
 * entry maps a CSS variable of the design onto the token name
 * `tailwind.config.js` uses, which `ThemeProvider` then feeds to NativeWind's
 * `vars()` at runtime.
 *
 * Regenerate rather than edit by hand when the web palette changes.
 */

export const THEME_NAMES = [
  "salbei",
  "lagune",
  "himmel",
  "indigo",
  "flieder",
  "terracotta",
  "ozean",
  "wald",
  "beere",
  "honig",
  "schiefer",
  "graphit",
] as const;

export type ThemeName = (typeof THEME_NAMES)[number];

/** The label shown in the picker. Names are proper nouns, so not translated. */
export const THEME_LABELS: Record<ThemeName, string> = {
  salbei: "Salbei",
  lagune: "Lagune",
  himmel: "Himmel",
  indigo: "Indigo",
  flieder: "Flieder",
  terracotta: "Terracotta",
  ozean: "Ozean",
  wald: "Wald",
  beere: "Beere",
  honig: "Honig",
  schiefer: "Schiefer",
  graphit: "Graphit",
};

export const THEMES: Record<ThemeName, Record<string, string>> = {
  salbei: {
    "--background": "#f7f5f0",
    "--card": "#ffffff",
    "--border": "#e7e2d7",
    "--foreground": "#26251f",
    "--muted-foreground": "#837d70",
    "--row-hover": "#faf8f2",
    "--field": "#f4f1e9",
    "--primary": "#3a7d44",
    "--primary-foreground": "#ffffff",
    "--accent": "#e4efe2",
    "--accent-foreground": "#316b3a",
    "--timer": "#24422a",
    "--timer-foreground": "#eef3e8",
    "--gold": "#e9c46a",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#efece1",
    "--status-slate-fg": "#77705d",
    "--status-sky-bg": "#e0ebe8",
    "--status-sky-fg": "#2f6459",
    "--status-amber-bg": "#f6ecd4",
    "--status-amber-fg": "#8a6414",
    "--status-green-bg": "#e4efe2",
    "--status-green-fg": "#316b3a",
    "--status-rose-bg": "#f7e3dd",
    "--status-rose-fg": "#a3452e",
  },
  lagune: {
    "--background": "#faf7f2",
    "--card": "#ffffff",
    "--border": "#ebe5d9",
    "--foreground": "#27272a",
    "--muted-foreground": "#8b8578",
    "--row-hover": "#fbf9f4",
    "--field": "#f5f1e8",
    "--primary": "#2a9d8f",
    "--primary-foreground": "#ffffff",
    "--accent": "#e2f1ee",
    "--accent-foreground": "#21867a",
    "--timer": "#14332d",
    "--timer-foreground": "#e4f1ee",
    "--gold": "#e9c46a",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#eeebe0",
    "--status-slate-fg": "#7b7462",
    "--status-sky-bg": "#ddf0ed",
    "--status-sky-fg": "#1f6d63",
    "--status-amber-bg": "#faeed2",
    "--status-amber-fg": "#96660f",
    "--status-green-bg": "#e3f0df",
    "--status-green-fg": "#3c7040",
    "--status-rose-bg": "#fbe4dc",
    "--status-rose-fg": "#bc4d26",
  },
  himmel: {
    "--background": "#f4f7fa",
    "--card": "#ffffff",
    "--border": "#e2e8f0",
    "--foreground": "#1f2732",
    "--muted-foreground": "#7b8698",
    "--row-hover": "#f7fafc",
    "--field": "#eef3f8",
    "--primary": "#2f7bd0",
    "--primary-foreground": "#ffffff",
    "--accent": "#e1eefb",
    "--accent-foreground": "#20639f",
    "--timer": "#16324f",
    "--timer-foreground": "#e2eefb",
    "--gold": "#f0b653",
    "--gold-foreground": "#4a3608",
    "--status-slate-bg": "#ebeef2",
    "--status-slate-fg": "#6f7787",
    "--status-sky-bg": "#dcedfb",
    "--status-sky-fg": "#1d6398",
    "--status-amber-bg": "#fceed0",
    "--status-amber-fg": "#92620d",
    "--status-green-bg": "#ddf2e3",
    "--status-green-fg": "#227540",
    "--status-rose-bg": "#fce3e4",
    "--status-rose-fg": "#b03844",
  },
  indigo: {
    "--background": "#f4f5fa",
    "--card": "#ffffff",
    "--border": "#e4e6ef",
    "--foreground": "#23252e",
    "--muted-foreground": "#7d8093",
    "--row-hover": "#f8f9fc",
    "--field": "#f1f2f8",
    "--primary": "#4f5dd8",
    "--primary-foreground": "#ffffff",
    "--accent": "#eaecfb",
    "--accent-foreground": "#3c47b8",
    "--timer": "#262c66",
    "--timer-foreground": "#e8eafd",
    "--gold": "#f0b653",
    "--gold-foreground": "#4a3608",
    "--status-slate-bg": "#edeef3",
    "--status-slate-fg": "#6d7085",
    "--status-sky-bg": "#ddedfb",
    "--status-sky-fg": "#1d5f96",
    "--status-amber-bg": "#fceed0",
    "--status-amber-fg": "#92620d",
    "--status-green-bg": "#ddf2e3",
    "--status-green-fg": "#227540",
    "--status-rose-bg": "#fce3e4",
    "--status-rose-fg": "#b03844",
  },
  flieder: {
    "--background": "#f7f5fa",
    "--card": "#ffffff",
    "--border": "#e8e3f0",
    "--foreground": "#28242e",
    "--muted-foreground": "#867f93",
    "--row-hover": "#faf8fc",
    "--field": "#f2eff7",
    "--primary": "#7d55cc",
    "--primary-foreground": "#ffffff",
    "--accent": "#eee6fa",
    "--accent-foreground": "#6440ad",
    "--timer": "#342550",
    "--timer-foreground": "#ebe3f8",
    "--gold": "#f0b653",
    "--gold-foreground": "#4a3608",
    "--status-slate-bg": "#edecf2",
    "--status-slate-fg": "#716d84",
    "--status-sky-bg": "#deecfa",
    "--status-sky-fg": "#1e6095",
    "--status-amber-bg": "#fbeed2",
    "--status-amber-fg": "#916310",
    "--status-green-bg": "#def1e2",
    "--status-green-fg": "#257341",
    "--status-rose-bg": "#fbe3e6",
    "--status-rose-fg": "#ae3a4e",
  },
  terracotta: {
    "--background": "#faf6f1",
    "--card": "#ffffff",
    "--border": "#ece1d4",
    "--foreground": "#2b241e",
    "--muted-foreground": "#8f8172",
    "--row-hover": "#fbf8f3",
    "--field": "#f5efe6",
    "--primary": "#bb5d3a",
    "--primary-foreground": "#ffffff",
    "--accent": "#f7e7dd",
    "--accent-foreground": "#9c4826",
    "--timer": "#46301f",
    "--timer-foreground": "#f5e8dc",
    "--gold": "#e9c46a",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#efe9df",
    "--status-slate-fg": "#7b7260",
    "--status-sky-bg": "#dfecea",
    "--status-sky-fg": "#2c6459",
    "--status-amber-bg": "#f8ecd0",
    "--status-amber-fg": "#8f6410",
    "--status-green-bg": "#e3efdd",
    "--status-green-fg": "#3a6f3e",
    "--status-rose-bg": "#f8e2da",
    "--status-rose-fg": "#a8432b",
  },
  ozean: {
    "--background": "#f3f7f8",
    "--card": "#ffffff",
    "--border": "#e0e9ec",
    "--foreground": "#1e2a2e",
    "--muted-foreground": "#75888e",
    "--row-hover": "#f6fafb",
    "--field": "#edf4f6",
    "--primary": "#20708d",
    "--primary-foreground": "#ffffff",
    "--accent": "#ddeef4",
    "--accent-foreground": "#175a73",
    "--timer": "#123642",
    "--timer-foreground": "#ddeef4",
    "--gold": "#eec25f",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#eaeef0",
    "--status-slate-fg": "#6c7d84",
    "--status-sky-bg": "#dcedfb",
    "--status-sky-fg": "#1d6398",
    "--status-amber-bg": "#fbeed1",
    "--status-amber-fg": "#916310",
    "--status-green-bg": "#ddf1e1",
    "--status-green-fg": "#25743e",
    "--status-rose-bg": "#fbe3e1",
    "--status-rose-fg": "#b04336",
  },
  wald: {
    "--background": "#f5f7f4",
    "--card": "#ffffff",
    "--border": "#e2e8de",
    "--foreground": "#212822",
    "--muted-foreground": "#7d887d",
    "--row-hover": "#f8faf6",
    "--field": "#eff3ec",
    "--primary": "#2d6a4f",
    "--primary-foreground": "#ffffff",
    "--accent": "#e0eee5",
    "--accent-foreground": "#215540",
    "--timer": "#1b3a2c",
    "--timer-foreground": "#e0eee5",
    "--gold": "#e9c46a",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#ebeee7",
    "--status-slate-fg": "#75806b",
    "--status-sky-bg": "#deedea",
    "--status-sky-fg": "#26685d",
    "--status-amber-bg": "#f7edd2",
    "--status-amber-fg": "#8d6412",
    "--status-green-bg": "#e1efdc",
    "--status-green-fg": "#356e3b",
    "--status-rose-bg": "#f8e3dc",
    "--status-rose-fg": "#a8462c",
  },
  beere: {
    "--background": "#faf6f8",
    "--card": "#ffffff",
    "--border": "#eee0e7",
    "--foreground": "#2b2226",
    "--muted-foreground": "#93808a",
    "--row-hover": "#fcf8fa",
    "--field": "#f6eef2",
    "--primary": "#a34d74",
    "--primary-foreground": "#ffffff",
    "--accent": "#f6e4ec",
    "--accent-foreground": "#8a3c5f",
    "--timer": "#4a2338",
    "--timer-foreground": "#f4e4ed",
    "--gold": "#f0b653",
    "--gold-foreground": "#4a3608",
    "--status-slate-bg": "#efeaed",
    "--status-slate-fg": "#7d707a",
    "--status-sky-bg": "#e0ebf8",
    "--status-sky-fg": "#22619a",
    "--status-amber-bg": "#fbeed2",
    "--status-amber-fg": "#916310",
    "--status-green-bg": "#e0f0e0",
    "--status-green-fg": "#2c7342",
    "--status-rose-bg": "#fae2de",
    "--status-rose-fg": "#b04330",
  },
  honig: {
    "--background": "#faf7f0",
    "--card": "#ffffff",
    "--border": "#ece3d0",
    "--foreground": "#2a251c",
    "--muted-foreground": "#8f8672",
    "--row-hover": "#fcf9f3",
    "--field": "#f5f0e4",
    "--primary": "#a97a24",
    "--primary-foreground": "#ffffff",
    "--accent": "#f5ead0",
    "--accent-foreground": "#8a6215",
    "--timer": "#3f3213",
    "--timer-foreground": "#f3ead4",
    "--gold": "#e9c46a",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#efece2",
    "--status-slate-fg": "#7c745e",
    "--status-sky-bg": "#e0ecf3",
    "--status-sky-fg": "#2a6484",
    "--status-amber-bg": "#f8ecd0",
    "--status-amber-fg": "#8f6410",
    "--status-green-bg": "#e5efdb",
    "--status-green-fg": "#3d6f38",
    "--status-rose-bg": "#f9e3da",
    "--status-rose-fg": "#ab4529",
  },
  schiefer: {
    "--background": "#f4f6f8",
    "--card": "#ffffff",
    "--border": "#e3e8ed",
    "--foreground": "#20262d",
    "--muted-foreground": "#7a8592",
    "--row-hover": "#f7f9fb",
    "--field": "#eef2f5",
    "--primary": "#42566b",
    "--primary-foreground": "#ffffff",
    "--accent": "#e2e9f0",
    "--accent-foreground": "#35485c",
    "--timer": "#22303e",
    "--timer-foreground": "#e2e9f0",
    "--gold": "#f0b653",
    "--gold-foreground": "#4a3608",
    "--status-slate-bg": "#eaedf1",
    "--status-slate-fg": "#6d7885",
    "--status-sky-bg": "#ddecfa",
    "--status-sky-fg": "#1d6095",
    "--status-amber-bg": "#fbeed1",
    "--status-amber-fg": "#916310",
    "--status-green-bg": "#def1e2",
    "--status-green-fg": "#26733f",
    "--status-rose-bg": "#fbe3e3",
    "--status-rose-fg": "#af3c40",
  },
  graphit: {
    "--background": "#f7f7f6",
    "--card": "#ffffff",
    "--border": "#e7e7e4",
    "--foreground": "#1c1c1a",
    "--muted-foreground": "#84847e",
    "--row-hover": "#fafaf9",
    "--field": "#f1f1ef",
    "--primary": "#1c1c1a",
    "--primary-foreground": "#ffffff",
    "--accent": "#ececea",
    "--accent-foreground": "#3a3a36",
    "--timer": "#1c1c1a",
    "--timer-foreground": "#f0f0ee",
    "--gold": "#e9c46a",
    "--gold-foreground": "#43350e",
    "--status-slate-bg": "#eef1f5",
    "--status-slate-fg": "#475569",
    "--status-sky-bg": "#e0f2fe",
    "--status-sky-fg": "#0369a1",
    "--status-amber-bg": "#fef3c7",
    "--status-amber-fg": "#92400e",
    "--status-green-bg": "#d1fae5",
    "--status-green-fg": "#065f46",
    "--status-rose-bg": "#ffe4e6",
    "--status-rose-fg": "#9f1239",
  },
};
