apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restart-production

resources:
  - ../base
  - ingress.yaml
  - secrets.yaml

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - DB_HOST=PRODUCTION_DB_HOST_PLACEHOLDER
      - ALLOWED_ORIGINS=https://app.colibri-app.ch
      - GOOGLE_AUTH_REDIRECT_URI=https://app.colibri-app.ch/api/auth/google/callback
      - AUTH_UI_REDIRECT=https://app.colibri-app.ch
