import { registerEnumType } from '@nestjs/graphql';

export enum PermissionCode {
  ORG_DELETE = 'ORG_DELETE',
  ORG_TRANSFER_OWNERSHIP = 'ORG_TRANSFER_OWNERSHIP',
  BILLING_MANAGE = 'BILLING_MANAGE',

  USER_INVITE = 'USER_INVITE',
  USER_REMOVE = 'USER_REMOVE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_ASSIGN = 'ROLE_ASSIGN',

  TEAM_CREATE = 'TEAM_CREATE',
  TEAM_DELETE = 'TEAM_DELETE',
  TEAM_MANAGE = 'TEAM_MANAGE',

  EMPLOYEE_READ = 'EMPLOYEE_READ',
  EMPLOYEE_WRITE = 'EMPLOYEE_WRITE',

  TIMESHEET_READ = 'TIMESHEET_READ',
  TIMESHEET_WRITE = 'TIMESHEET_WRITE',

  SCHOOL_CLASS_READ = 'SCHOOL_CLASS_READ',
  SCHOOL_CLASS_WRITE = 'SCHOOL_CLASS_WRITE',
  SCHOOL_CLASS_DELETE = 'SCHOOL_CLASS_DELETE',

  CONTACT_PERSON_READ = 'CONTACT_PERSON_READ',
  CONTACT_PERSON_WRITE = 'CONTACT_PERSON_WRITE',
  CONTACT_PERSON_DELETE = 'CONTACT_PERSON_DELETE',

  ADMISSION_STAGE_READ = 'ADMISSION_STAGE_READ',
  ADMISSION_STAGE_MANAGE = 'ADMISSION_STAGE_MANAGE',

  CURRICULUM_LEVEL_READ = 'CURRICULUM_LEVEL_READ',
  CURRICULUM_LEVEL_MANAGE = 'CURRICULUM_LEVEL_MANAGE',

  CURRICULUM_READ = 'CURRICULUM_READ',
  CURRICULUM_MANAGE = 'CURRICULUM_MANAGE',

  ADDRESS_READ = 'ADDRESS_READ',
  ADDRESS_WRITE = 'ADDRESS_WRITE',
  ADDRESS_DELETE = 'ADDRESS_DELETE',
}

registerEnumType(PermissionCode, {
  name: 'PermissionCode',
  description: 'Supported Permission Codes',
});
