import { registerEnumType } from '@nestjs/graphql';

export enum PermissionCode {
  ORG_DELETE = 'ORG_DELETE',
  ORG_TRANSFER_OWNERSHIP = 'ORG_TRANSFER_OWNERSHIP',
  BILLING_MANAGE = 'BILLING_MANAGE',

  USER_INVITE = 'USER_INVITE',
  USER_REMOVE = 'USER_REMOVE',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_ASSIGN = 'ROLE_ASSIGN',

  TEAM_CREATE = 'TEAM_CREATE',
  TEAM_DELETE = 'TEAM_DELETE',
  TEAM_MANAGE = 'TEAM_MANAGE',

  EMPLOYEE_READ = 'EMPLOYEE_READ',
  EMPLOYEE_WRITE = 'EMPLOYEE_WRITE',

  EMPLOYEE_ABSENCE_CATEGORY_READ = 'EMPLOYEE_ABSENCE_CATEGORY_READ',
  EMPLOYEE_ABSENCE_CATEGORY_MANAGE = 'EMPLOYEE_ABSENCE_CATEGORY_MANAGE',

  TIMESHEET_READ = 'TIMESHEET_READ',
  TIMESHEET_WRITE = 'TIMESHEET_WRITE',

  SCHOOL_CLASS_READ = 'SCHOOL_CLASS_READ',
  SCHOOL_CLASS_WRITE = 'SCHOOL_CLASS_WRITE',
  SCHOOL_CLASS_DELETE = 'SCHOOL_CLASS_DELETE',

  CONTACT_PERSON_READ = 'CONTACT_PERSON_READ',
  CONTACT_PERSON_WRITE = 'CONTACT_PERSON_WRITE',
  CONTACT_PERSON_DELETE = 'CONTACT_PERSON_DELETE',

  ADMISSION_STAGE_READ = 'ADMISSION_STAGE_READ',
  ADMISSION_STAGE_MANAGE = 'ADMISSION_STAGE_MANAGE',

  ADMISSION_APPLICATION_READ = 'ADMISSION_APPLICATION_READ',
  ADMISSION_APPLICATION_WRITE = 'ADMISSION_APPLICATION_WRITE',
  ADMISSION_APPLICATION_MOVE = 'ADMISSION_APPLICATION_MOVE',
  ADMISSION_APPLICATION_ENROLL = 'ADMISSION_APPLICATION_ENROLL',
  ADMISSION_APPLICATION_DELETE = 'ADMISSION_APPLICATION_DELETE',

  ADMISSION_EMAIL_TEMPLATE_MANAGE = 'ADMISSION_EMAIL_TEMPLATE_MANAGE',
  ADMISSION_EMAIL_SEND = 'ADMISSION_EMAIL_SEND',

  FAMILY_READ = 'FAMILY_READ',
  FAMILY_WRITE = 'FAMILY_WRITE',

  CURRICULUM_LEVEL_READ = 'CURRICULUM_LEVEL_READ',
  CURRICULUM_LEVEL_MANAGE = 'CURRICULUM_LEVEL_MANAGE',

  CURRICULUM_READ = 'CURRICULUM_READ',
  CURRICULUM_MANAGE = 'CURRICULUM_MANAGE',

  RECORD_KEEPING_READ = 'RECORD_KEEPING_READ',
  RECORD_KEEPING_WRITE = 'RECORD_KEEPING_WRITE',
  RECORD_KEEPING_SETTINGS_MANAGE = 'RECORD_KEEPING_SETTINGS_MANAGE',

  ADDRESS_READ = 'ADDRESS_READ',
  ADDRESS_WRITE = 'ADDRESS_WRITE',
  ADDRESS_DELETE = 'ADDRESS_DELETE',

  PROJECT_READ = 'PROJECT_READ',
  PROJECT_CREATE = 'PROJECT_CREATE',
  PROJECT_MANAGE_ALL = 'PROJECT_MANAGE_ALL',
  PROJECT_TEMPLATE_MANAGE = 'PROJECT_TEMPLATE_MANAGE',
}

registerEnumType(PermissionCode, {
  name: 'PermissionCode',
  description: 'Supported Permission Codes',
});
